name: mpc_dart
description: Safeamtrix mpc dart package, ecdsa, eddsa and bls supported.
version: 1.4.5
homepage: https://sbtauth.io

environment:
  sdk: '>=2.18.1 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  pointycastle: ^3.6.2
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^6.1.2

ffigen:
  output: 'lib/ffi/ffi.dart'
  headers:
    entry-points:
      - 'native/binding.h'
  
flutter:
  plugin:
    platforms:
      android:
        package: io.sbtauth.mpc_dart
        pluginClass: MpcDartPlugin
      ios:
        pluginClass: MpcDartPlugin
